--
-- Table document_space_action
--
REPLACE INTO document_space_action (id_action, name_key, description_key, action_url, icon_url, action_permission) VALUES (1, 'document.spaces.action.createSpace.name', 'document.spaces.action.createSpace.description', 'jsp/admin/plugins/document/CreateSpace.jsp', 'fam-folder-bell', 'CREATE');
REPLACE INTO document_space_action (id_action, name_key, description_key, action_url, icon_url, action_permission) VALUES (2, 'document.spaces.action.deleteSpace.name', 'document.spaces.action.deleteSpace.description', 'jsp/admin/plugins/document/DeleteSpace.jsp', 'fam-folder-edit', 'DELETE');
REPLACE INTO document_space_action (id_action, name_key, description_key, action_url, icon_url, action_permission) VALUES (3, 'document.spaces.action.modifySpace.name', 'document.spaces.action.modifySpace.description', 'jsp/admin/plugins/document/ModifySpace.jsp', 'fam-folder-error', 'MODIFY');
REPLACE INTO document_space_action (id_action, name_key, description_key, action_url, icon_url, action_permission) VALUES (4, 'document.spaces.action.manageUsers.name', 'document.spaces.action.manageUsers.description', 'jsp/admin/plugins/document/ManageSpaceUsers.jsp', 'fam-folder-wrench', 'USERS');
REPLACE INTO document_space_action (id_action, name_key, description_key, action_url, icon_url, action_permission) VALUES (5, 'document.spaces.action.moveSpace.name', 'document.spaces.action.moveSpace.description', 'jsp/admin/plugins/document/MoveSpace.jsp', 'fam-folder-heart', 'MOVE');

--
-- Table document_workflow_action
--
REPLACE INTO document_workflow_action (id_action, name_key, description_key, action_url, icon_url, action_permission, id_finish_state) VALUES (1, 'document.workflow.action.deleteDocument.name', 'document.workflow.action.deleteDocument.description', 'jsp/admin/plugins/document/DeleteDocument.jsp?', 'fam-delete', 'DELETE', NULL);
REPLACE INTO document_workflow_action (id_action, name_key, description_key, action_url, icon_url, action_permission, id_finish_state) VALUES (2, 'document.workflow.action.modifyDocument.name', 'document.workflow.action.modifyDocument.description', 'jsp/admin/plugins/document/ModifyDocument.jsp?', 'fam-page-white-excel', 'MODIFY', NULL);
REPLACE INTO document_workflow_action (id_action, name_key, description_key, action_url, icon_url, action_permission, id_finish_state) VALUES (3, 'document.workflow.action.submitForApproval.name', 'document.workflow.action.submitForApproval.description', 'jsp/admin/plugins/document/DoChangeState.jsp?id_state=2&amp;', 'fam-page-white-magnify', 'SUBMIT', 2);
REPLACE INTO document_workflow_action (id_action, name_key, description_key, action_url, icon_url, action_permission, id_finish_state) VALUES (4, 'document.workflow.action.approveDocument.name', 'document.workflow.action.approveDocument.description', 'jsp/admin/plugins/document/DoValidateDocument.jsp?id_state=3&amp;', 'fam-accept', 'VALIDATE', 3);
REPLACE INTO document_workflow_action (id_action, name_key, description_key, action_url, icon_url, action_permission, id_finish_state) VALUES (5, 'document.workflow.action.assignDocument.name', 'document.workflow.action.assignDocument.description', 'jsp/admin/plugins/document/ManageDocumentPublishing.jsp?', 'fam-page-white-zip', 'ASSIGN', NULL);
REPLACE INTO document_workflow_action (id_action, name_key, description_key, action_url, icon_url, action_permission, id_finish_state) VALUES (6, 'document.workflow.action.rejectDocument.name', 'document.workflow.action.rejectDocument.description', 'jsp/admin/plugins/document/DoChangeState.jsp?id_state=4&amp;', 'fam-stop', 'VALIDATE', 4);
REPLACE INTO document_workflow_action (id_action, name_key, description_key, action_url, icon_url, action_permission, id_finish_state) VALUES (7, 'document.workflow.action.submitAgain.name', 'document.workflow.action.submitAgain.description', 'jsp/admin/plugins/document/DoChangeState.jsp?id_state=2&amp;', 'fam-page-white-magnify', 'SUBMIT', 2);
REPLACE INTO document_workflow_action (id_action, name_key, description_key, action_url, icon_url, action_permission, id_finish_state) VALUES (8, 'document.workflow.action.archiveDocument.name', 'document.workflow.action.archiveDocument.description', 'jsp/admin/plugins/document/DoConfirmArchiveDocument.jsp?id_state=5&amp;', 'fam-page-white-edit', 'ARCHIVE', 5);
REPLACE INTO document_workflow_action (id_action, name_key, description_key, action_url, icon_url, action_permission, id_finish_state) VALUES (9, 'document.workflow.action.changeDocument.name', 'document.workflow.action.changeDocument.description', 'jsp/admin/plugins/document/ModifyDocument.jsp?id_state=6&amp;', 'fam-page-white-excel', 'CHANGE', 6);
REPLACE INTO document_workflow_action (id_action, name_key, description_key, action_url, icon_url, action_permission, id_finish_state) VALUES (10, 'document.workflow.action.submitChanges.name', 'document.workflow.action.submitChanges.description', 'jsp/admin/plugins/document/DoChangeState.jsp?id_state=7&amp;', 'fam-page-white-magnify', 'SUBMIT', 7);
REPLACE INTO document_workflow_action (id_action, name_key, description_key, action_url, icon_url, action_permission, id_finish_state) VALUES (11, 'document.workflow.action.rejectChanges.name', 'document.workflow.action.rejectChanges.description', 'jsp/admin/plugins/document/DoChangeState.jsp?id_state=6&amp;', 'fam-stop', 'VALIDATE', 6);
REPLACE INTO document_workflow_action (id_action, name_key, description_key, action_url, icon_url, action_permission, id_finish_state) VALUES (12, 'document.workflow.action.approveChanges.name', 'document.workflow.action.approveChanges.description', 'jsp/admin/plugins/document/DoValidateDocument.jsp?id_state=3&amp;', 'fam-accept', 'VALIDATE', 3);
REPLACE INTO document_workflow_action (id_action, name_key, description_key, action_url, icon_url, action_permission, id_finish_state) VALUES (13, 'document.workflow.action.unarchiveDocument.name', 'document.workflow.action.unarchiveDocument.description', 'jsp/admin/plugins/document/DoChangeState.jsp?id_state=3&amp;', 'fam-package-go', 'ARCHIVE', 3);
REPLACE INTO document_workflow_action (id_action, name_key, description_key, action_url, icon_url, action_permission, id_finish_state) VALUES (14, 'document.workflow.action.history.name', 'document.workflow.action.history.description', 'jsp/admin/plugins/document/DocumentHistory.jsp?', 'fam-book-previous', 'VIEW_HISTORY', NULL);
REPLACE INTO document_workflow_action (id_action, name_key, description_key, action_url, icon_url, action_permission, id_finish_state) VALUES (15, 'document.workflow.action.previewDocument.name', 'document.workflow.action.previewDocument.description', 'jsp/admin/plugins/document/PreviewDocument.jsp?', 'fam-eye', 'VIEW', NULL);
REPLACE INTO document_workflow_action (id_action, name_key, description_key, action_url, icon_url, action_permission, id_finish_state) VALUES (16, 'document.workflow.action.moveDocument.name', 'document.workflow.action.moveDocument.description', 'jsp/admin/plugins/document/MoveDocument.jsp?', 'fam-folder-heart', 'MOVE', NULL);
REPLACE INTO document_workflow_action (id_action, name_key, description_key, action_url, icon_url, action_permission, id_finish_state) VALUES (17, 'document.workflow.action.commentDocument.name', 'document.workflow.action.commentDocument.description', 'jsp/admin/plugins/document/modules/comment/ManageDocumentComments.jsp?', 'fam-comment-add', 'COMMENT', NULL);
REPLACE INTO document_workflow_action (id_action, name_key, description_key, action_url, icon_url, action_permission, id_finish_state) VALUES (18, 'document.workflow.action.publishDocument.name', 'document.workflow.action.publishDocument.description', NULL, NULL, 'PUBLISH', NULL);
