-- liquibase formatted sql
-- changeset document:update_db_document-5.1.1-6.0.0.sql
-- preconditions onFail:MARK_RAN onError:WARN
--
-- Add AUTO_INCREMENT to primary keys
--
ALTER TABLE document MODIFY COLUMN id_document int AUTO_INCREMENT;
ALTER TABLE document_type_attr MODIFY COLUMN id_document_attr int AUTO_INCREMENT;
ALTER TABLE document_category MODIFY COLUMN id_category int AUTO_INCREMENT;
ALTER TABLE document_rule MODIFY COLUMN id_rule int AUTO_INCREMENT;
ALTER TABLE document_indexer_action MODIFY COLUMN id_action int AUTO_INCREMENT;
ALTER TABLE document_page_template MODIFY COLUMN id_page_template_document int AUTO_INCREMENT;


-- changeset document:update_db_document-5.1.1-6.0.0-mariaDB-mySQL.sql dbms:mariadb,mysql
SET SESSION sql_mode='NO_AUTO_VALUE_ON_ZERO';
ALTER TABLE document_space MODIFY COLUMN id_space int AUTO_INCREMENT;


-- changeset document:update_db_document-5.1.1-6.0.0-postgreSQL.sql dbms:postgresql

-- Default value on id_space column is dropped because PostgreSQL doesn't allow to switch to an auto-increment
ALTER TABLE document_space alter id_space drop default;

-- Switch to auto-increment primary key
ALTER TABLE document_space alter id_space add GENERATED by default AS IDENTITY(START WITH 1);

-- The query below is used to synchronize the sequence created previously with the content of document_space table.
SELECT setval((SELECT PG_GET_SERIAL_SEQUENCE('"document_space"', 'id_space')), (SELECT MAX(id_space) FROM document_space));