-- liquibase formatted sql
-- changeset document:update_db_document-5.1.1-6.0.0.sql
-- preconditions onFail:MARK_RAN onError:WARN
--
-- Add AUTO_INCREMENT to primary keys
--
ALTER TABLE document MODIFY COLUMN id_document int AUTO_INCREMENT;
ALTER TABLE document_type_attr MODIFY COLUMN id_document_attr int AUTO_INCREMENT;
ALTER TABLE document_category MODIFY COLUMN id_category int AUTO_INCREMENT;
ALTER TABLE document_rule MODIFY COLUMN id_rule int AUTO_INCREMENT;
ALTER TABLE document_indexer_action MODIFY COLUMN id_action int AUTO_INCREMENT;
ALTER TABLE document_page_template MODIFY COLUMN id_page_template_document int AUTO_INCREMENT;

-- changeset document:update_db_document-5.1.1-6.0.0-mariaDB-mySQL.sql dbms:mariadb,mysql
SET SESSION sql_mode='NO_AUTO_VALUE_ON_ZERO';
ALTER TABLE document_space MODIFY COLUMN id_space int AUTO_INCREMENT;

-- changeset document:update_db_document-5.1.1-6.0.0-postgreSQL.sql dbms:postgresql

-- Default value on id_space column is dropped because PostgreSQL doesn't allow to switch to an auto-increment
ALTER TABLE document_space alter id_space drop default;

-- Switch to auto-increment primary key
ALTER TABLE document_space alter id_space add GENERATED by default AS IDENTITY(START WITH 1);

-- The query below is used to synchronize the sequence created previously with the content of document_space table.
SELECT setval((SELECT PG_GET_SERIAL_SEQUENCE('"document_space"', 'id_space')), (SELECT MAX(id_space) FROM document_space));

-- changeset document:update_db_document-5.1.1-6.0.0-rev1.sql
-- Remove and add space icons
DELETE FROM document_space_icon;
INSERT INTO document_space_icon VALUES (1, 'themes\\shared\\plugins\\document\\images\\spaces\\folder.svg');
INSERT INTO document_space_icon VALUES (2, 'themes\\shared\\plugins\\document\\images\\spaces\\folder-down.svg');
INSERT INTO document_space_icon VALUES (3, 'themes\\shared\\plugins\\document\\images\\spaces\\folder-x.svg');
INSERT INTO document_space_icon VALUES (4, 'themes\\shared\\plugins\\document\\images\\spaces\\folder-cog.svg');
INSERT INTO document_space_icon VALUES (5, 'themes\\shared\\plugins\\document\\images\\spaces\\folder-check.svg');
INSERT INTO document_space_icon VALUES (6, 'themes\\shared\\plugins\\document\\images\\spaces\\folder-bolt.svg');
INSERT INTO document_space_icon VALUES (7, 'themes\\shared\\plugins\\document\\images\\spaces\\folder-root.svg');
INSERT INTO document_space_icon VALUES (8, 'themes\\shared\\plugins\\document\\images\\spaces\\folder-photo.svg');
INSERT INTO document_space_icon VALUES (9, 'themes\\shared\\plugins\\document\\images\\spaces\\folder-star.svg');
INSERT INTO document_space_icon VALUES (10, 'themes\\shared\\plugins\\document\\images\\spaces\\folder-exclamation.svg');
INSERT INTO document_space_icon VALUES (11, 'themes\\shared\\plugins\\document\\images\\spaces\\folder-heart.svg');
INSERT INTO document_space_icon VALUES (12, 'themes\\shared\\plugins\\document\\images\\spaces\\folder-photo-up.svg');

-- Remove and add templates icons
DELETE FROM document_page_template;
INSERT INTO document_page_template (page_template_path,picture_path,description) VALUES ('/skin/plugins/document/document_content_service.html','themes/shared/plugins/document/images/page_templates/page_template_document0.png','Défaut');
INSERT INTO document_page_template (page_template_path,picture_path,description) VALUES ('/skin/plugins/document/page_templates/page_template_document1.html','themes/shared/plugins/document/images/page_templates/page_template_document1.png','Pleine page');
INSERT INTO document_page_template (page_template_path,picture_path,description) VALUES ('/skin/plugins/document/page_templates/page_template_document2.html','themes/shared/plugins/document/images/page_templates/page_template_document2.png','Rubrique en-dessous');

-- Remove and add space actions icons
DELETE FROM document_space_action WHERE id_action=1;
INSERT INTO document_space_action VALUES (1, 'document.spaces.action.createSpace.name', 'document.spaces.action.createSpace.description', 'jsp/admin/plugins/document/CreateSpace.jsp', 'plus', 'CREATE');
DELETE FROM document_space_action WHERE id_action=2;
INSERT INTO document_space_action VALUES (2, 'document.spaces.action.deleteSpace.name', 'document.spaces.action.deleteSpace.description', 'jsp/admin/plugins/document/DeleteSpace.jsp', 'trash', 'DELETE');
DELETE FROM document_space_action WHERE id_action=3;
INSERT INTO document_space_action VALUES (3, 'document.spaces.action.modifySpace.name', 'document.spaces.action.modifySpace.description', 'jsp/admin/plugins/document/ModifySpace.jsp', 'edit', 'MODIFY');
DELETE FROM document_space_action WHERE id_action=4;
INSERT INTO document_space_action VALUES (4, 'document.spaces.action.manageUsers.name', 'document.spaces.action.manageUsers.description', 'jsp/admin/plugins/document/ManageSpaceUsers.jsp', 'user', 'USERS');
DELETE FROM document_space_action WHERE id_action=5;
INSERT INTO document_space_action VALUES (5, 'document.spaces.action.moveSpace.name', 'document.spaces.action.moveSpace.description', 'jsp/admin/plugins/document/MoveSpace.jsp', 'arrows-alt', 'MOVE');

-- Remove and add document workflow actions icons
DELETE FROM document_workflow_action WHERE id_action=1;
INSERT INTO document_workflow_action VALUES (1, 'document.workflow.action.deleteDocument.name', 'document.workflow.action.deleteDocument.description', 'jsp/admin/plugins/document/DeleteDocument.jsp?', 'trash', 'DELETE', NULL);
DELETE FROM document_workflow_action WHERE id_action=2;
INSERT INTO document_workflow_action VALUES (2, 'document.workflow.action.modifyDocument.name', 'document.workflow.action.modifyDocument.description', 'jsp/admin/plugins/document/ModifyDocument.jsp?', 'edit', 'MODIFY', NULL);
DELETE FROM document_workflow_action WHERE id_action=3;
INSERT INTO document_workflow_action VALUES (3, 'document.workflow.action.submitForApproval.name', 'document.workflow.action.submitForApproval.description', 'jsp/admin/plugins/document/DoChangeState.jsp?id_state=2&amp;', 'cog', 'SUBMIT', 2);
DELETE FROM document_workflow_action WHERE id_action=4;
INSERT INTO document_workflow_action VALUES (4, 'document.workflow.action.approveDocument.name', 'document.workflow.action.approveDocument.description', 'jsp/admin/plugins/document/DoValidateDocument.jsp?id_state=3&amp;', 'check', 'VALIDATE', 3);
DELETE FROM document_workflow_action WHERE id_action=5;
INSERT INTO document_workflow_action VALUES (5, 'document.workflow.action.assignDocument.name', 'document.workflow.action.assignDocument.description', 'jsp/admin/plugins/document/ManageDocumentPublishing.jsp?', 'globe', 'ASSIGN', NULL);
DELETE FROM document_workflow_action WHERE id_action=6;
INSERT INTO document_workflow_action VALUES (6, 'document.workflow.action.rejectDocument.name', 'document.workflow.action.rejectDocument.description', 'jsp/admin/plugins/document/DoChangeState.jsp?id_state=4&amp;', 'minus', 'VALIDATE', 4);
DELETE FROM document_workflow_action WHERE id_action=7;
INSERT INTO document_workflow_action VALUES (7, 'document.workflow.action.submitAgain.name', 'document.workflow.action.submitAgain.description', 'jsp/admin/plugins/document/DoChangeState.jsp?id_state=2&amp;', 'check', 'SUBMIT', 2);
DELETE FROM document_workflow_action WHERE id_action=8;
INSERT INTO document_workflow_action VALUES (8, 'document.workflow.action.archiveDocument.name', 'document.workflow.action.archiveDocument.description', 'jsp/admin/plugins/document/DoConfirmArchiveDocument.jsp?id_state=5&amp;', 'download', 'ARCHIVE', 5);
DELETE FROM document_workflow_action WHERE id_action=9;
INSERT INTO document_workflow_action VALUES (9, 'document.workflow.action.changeDocument.name', 'document.workflow.action.changeDocument.description', 'jsp/admin/plugins/document/ModifyDocument.jsp?id_state=6&amp;', 'edit', 'CHANGE', 6);
DELETE FROM document_workflow_action WHERE id_action=10;
INSERT INTO document_workflow_action VALUES (10, 'document.workflow.action.submitChanges.name', 'document.workflow.action.submitChanges.description', 'jsp/admin/plugins/document/DoChangeState.jsp?id_state=7&amp;', 'cog', 'SUBMIT', 7);
DELETE FROM document_workflow_action WHERE id_action=11;
INSERT INTO document_workflow_action VALUES (11, 'document.workflow.action.rejectChanges.name', 'document.workflow.action.rejectChanges.description', 'jsp/admin/plugins/document/DoChangeState.jsp?id_state=6&amp;', 'minus', 'VALIDATE', 6);
DELETE FROM document_workflow_action WHERE id_action=12;
INSERT INTO document_workflow_action VALUES (12, 'document.workflow.action.approveChanges.name', 'document.workflow.action.approveChanges.description', 'jsp/admin/plugins/document/DoValidateDocument.jsp?id_state=3&amp;', 'check', 'VALIDATE', 3);
DELETE FROM document_workflow_action WHERE id_action=13;
INSERT INTO document_workflow_action VALUES (13, 'document.workflow.action.unarchiveDocument.name', 'document.workflow.action.unarchiveDocument.description', 'jsp/admin/plugins/document/DoChangeState.jsp?id_state=3&amp;', 'upload', 'ARCHIVE', 3);
DELETE FROM document_workflow_action WHERE id_action=14;
INSERT INTO document_workflow_action VALUES (14, 'document.workflow.action.history.name', 'document.workflow.action.history.description', 'jsp/admin/plugins/document/DocumentHistory.jsp?', 'list', 'VIEW_HISTORY', NULL);
DELETE FROM document_workflow_action WHERE id_action=15;
INSERT INTO document_workflow_action VALUES (15, 'document.workflow.action.previewDocument.name', 'document.workflow.action.previewDocument.description', 'jsp/admin/plugins/document/PreviewDocument.jsp?', 'eye', 'VIEW', NULL);
DELETE FROM document_workflow_action WHERE id_action=16;
INSERT INTO document_workflow_action VALUES (16, 'document.workflow.action.moveDocument.name', 'document.workflow.action.moveDocument.description', 'jsp/admin/plugins/document/MoveDocument.jsp?', 'arrows-alt', 'MOVE', NULL);
DELETE FROM document_workflow_action WHERE id_action=18;
INSERT INTO document_workflow_action VALUES (18, 'document.workflow.action.publishDocument.name', 'document.workflow.action.publishDocument.description', NULL, 'globe', 'PUBLISH', NULL);
