-- liquibase formatted sql
-- changeset document:update_db_document-5.1.1-6.0.0.sql
-- preconditions onFail:MARK_RAN onError:WARN
--
-- Add AUTO_INCREMENT to primary keys
--
ALTER TABLE document MODIFY COLUMN id_document int AUTO_INCREMENT;
ALTER TABLE document_type_attr MODIFY COLUMN id_document_attr int AUTO_INCREMENT;
ALTER TABLE document_category MODIFY COLUMN id_category int AUTO_INCREMENT;
ALTER TABLE document_rule MODIFY COLUMN id_rule int AUTO_INCREMENT;
ALTER TABLE document_indexer_action MODIFY COLUMN id_action int AUTO_INCREMENT;
ALTER TABLE document_page_template MODIFY COLUMN id_page_template_document int AUTO_INCREMENT;

-- changeset document:update_db_document-5.1.1-6.0.0-mariaDB-mySQL.sql dbms:mariadb,mysql
SET SESSION sql_mode='NO_AUTO_VALUE_ON_ZERO';
ALTER TABLE document_space MODIFY COLUMN id_space int AUTO_INCREMENT;

-- changeset document:update_db_document-5.1.1-6.0.0-postgreSQL.sql dbms:postgresql

-- Default value on id_space column is dropped because PostgreSQL doesn't allow to switch to an auto-increment
ALTER TABLE document_space alter id_space drop default;

-- Switch to auto-increment primary key
ALTER TABLE document_space alter id_space add GENERATED by default AS IDENTITY(START WITH 1);

-- The query below is used to synchronize the sequence created previously with the content of document_space table.
SELECT setval((SELECT PG_GET_SERIAL_SEQUENCE('"document_space"', 'id_space')), (SELECT MAX(id_space) FROM document_space));

-- Remove and add space icons
DELETE FROM document_space_icon;
INSERT INTO document_space_icon VALUES (1, 'themes\\shared\\plugins\\document\\images\\spaces\\folder.svg');
INSERT INTO document_space_icon VALUES (2, 'themes\\shared\\plugins\\document\\images\\spaces\\folder-down.svg');
INSERT INTO document_space_icon VALUES (3, 'themes\\shared\\plugins\\document\\images\\spaces\\folder-x.svg');
INSERT INTO document_space_icon VALUES (4, 'themes\\shared\\plugins\\document\\images\\spaces\\folder-cog.svg');
INSERT INTO document_space_icon VALUES (5, 'themes\\shared\\plugins\\document\\images\\spaces\\folder-check.svg');
INSERT INTO document_space_icon VALUES (6, 'themes\\shared\\plugins\\document\\images\\spaces\\folder-bolt.svg');
INSERT INTO document_space_icon VALUES (7, 'themes\\shared\\plugins\\document\\images\\spaces\\folder-root.svg');
INSERT INTO document_space_icon VALUES (8, 'themes\\shared\\plugins\\document\\images\\spaces\\folder-photo.svg');
INSERT INTO document_space_icon VALUES (9, 'themes\\shared\\plugins\\document\\images\\spaces\\folder-star.svg');
INSERT INTO document_space_icon VALUES (10, 'themes\\shared\\plugins\\document\\images\\spaces\\folder-exclamation.svg');
INSERT INTO document_space_icon VALUES (11, 'themes\\shared\\plugins\\document\\images\\spaces\\folder-heart.svg');
INSERT INTO document_space_icon VALUES (12, 'themes\\shared\\plugins\\document\\images\\spaces\\folder-photo-up.svg');

-- Remove and add templates icons
DELETE FROM document_page_template;
INSERT INTO document_page_template (page_template_path,picture_path,description) VALUES ('/skin/plugins/document/document_content_service.html','themes/shared/plugins/document/images/page_templates/page_template_document0.png','Défaut');
INSERT INTO document_page_template (page_template_path,picture_path,description) VALUES ('/skin/plugins/document/page_templates/page_template_document1.html','themes/shared/plugins/document/images/page_templates/page_template_document1.png','Pleine page');
INSERT INTO document_page_template (page_template_path,picture_path,description) VALUES ('/skin/plugins/document/page_templates/page_template_document2.html','themes/shared/plugins/document/images/page_templates/page_template_document2.png','Rubrique en-dessous');